#
# Copyright 2015-2021 Jeeva Kandasamy (jkandasa@gmail.com)
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


name: Builds and publish packages to google drive

on:
  push:
    branches: [ development ]

jobs:
  setup:
    name: Build and publish packages to google drive
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install transifex-client
      run: |
        python -m pip install --upgrade pip
        pip install transifex-client

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # to avoid license year issue
    - uses: docker/setup-buildx-action@v1

    - name: Login in to docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: sync transifex
      run: scripts/sync_transifex.sh
      env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_MC_V1_TOKEN }}

    - name: commit transifex changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Sync transifex changes
        branch: development
        commit_options: '--no-verify --signoff'
        file_pattern: dist/src/main/package/www/languages/*.json dist/src/main/resources/*.properties
        commit_user_name: Jeeva Kandasamy
        commit_user_email: jkandasa@gmail.com
        commit_author: Jeeva Kandasamy <jkandasa@gmail.com>

    - name: do package
      run: ./scripts/build.sh

    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.GOOGLE_SKICKA_TOKENCACHE_JSON }}
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        upload-from: ./builds
        upload-to: ${{ secrets.GOOGLE_DRIVE_MC1_SNAPSHOT_PATH }}
